version: '3.8'

services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports: 
            - "8081:8081"
        volumes:
            - "/app/node_modules" 
            - ".:/app"